import type { Metadata } from 'next'
import { openS } from './ui/fonts/fonts'
import './globals.css'
import Nav from './ui/components/Nav'
import Footer from './ui/components/Footer'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={openS.className + " bg-gray-50"}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
